### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by Misiu** [smsapi/smsapi-csharp-client#11]
W chwili obecnej podczas dodawania biblioteki do projektu z .NET Core 2.1 dostaję następujący warning:

> Package 'SMSAPI.pl 1.0.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

Czy planują Państwo wydanie wersji ze wsparciem dla .NET Core?

**Comment by Misiu** [comment]
@pdzieniszewski jakieś postępy jeśli chodzi o wsparcie dla .NET Core/ .NET Standard ?

**Comment by pwasiewicz** [comment]
@Misiu jako, że to jest projekt an GH, możesz sciągnąć źródła i skompilować projekt do .NET Core. Żadnych przeróbek nie potrzebujesz, kod akruat jest tak napisany, że spokojnie się to uda (pamiętając tylko, że trzeab zmienić strukturę csproja).
BTW, temu przydałby się porządnych refaktor (użycie np. RestSharpa zamiast ręcznie budowania formularza) i wspracie dla asynców. To chyba bardziej plące ;)

**Comment by Misiu** [comment]
@pwasiewicz tak zrobiłem :) Drobna zmiana w csproj i śmiga na .NET Core.
Async muszą być koniecznie, przebudowuję bibliotekę lokalnie, ale tak jak piszesz przydałby się porządny refactor na ReshSharp'a.
Moze kiedyś @smsapi się tym zajmie...

**Comment by smsapi** [comment]
Dodaliśmy aktualizację do biblioteki.

**Comment by Misiu** [comment]
@smsapi dziękuję za implementację.
