### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by GrzegorzSzwed** [smsapi/smsapi-csharp-client#14]
I have a problem with App.config configuration.

When I use few accounts with another user on each account on https://www.smsapi.com, then which credentials should be in app.config? I cannot figure it out. 

On one account sms are working when on the another account they are not sending.

**Comment by smsapi** [comment]
Hello, please contact our tech support on https://www.smsapi.pl/kontakt (if you are using PL version) or https://www.smsapi.com/en/contact (if you are using international version).
