### ISSUE TITLE
TestSendGetDelete  threw exception

### ISSUE THREAD

**Issue by jaszczykj** [smsapi/smsapi-csharp-client#18]
Zasób nie istnieje: https://www.smsapi.pl/assets/img/mms.jpg
Poprawcie test lub link do zasobu. 

Message: 
    Test method smsapiTests.MmsTest.TestSendGetDelete threw exception: 
    SMSApi.Api.ActionException: Remote get error: https://www.smsapi.pl/assets/img/mms.jpg
  Stack Trace: 
    Base`2.HandleError(Stream data) line 109
    Base`2.Execute() line 68
    MmsTest.TestSendGetDelete() line 12

**Comment by smsapi** [comment]
Poprawione
