### ISSUE TITLE
Deserialization raises an exception

### ISSUE THREAD

**Issue by anddrzejb** [smsapi/smsapi-csharp-client#24]
When the library is trying to deserialize response into SMSApi.Api.Response.Error in Base.cs (line 35), an exception is thrown:

System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=The data contract type 'SMSApi.Api.Response.Error' cannot be deserialized because the required data member 'error' was not found.
  Source=System.Private.DataContractSerialization
  StackTrace:
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowMissingRequiredMembers(Object obj, XmlDictionaryString[] memberNames, Byte[] expectedElements, Byte[] requiredElements)

Tested on Core 3.1.

**Comment by takczyowak** [comment]
Hello!
Could you please check if that excpetions still exists?

**Comment by anddrzejb** [comment]
Looks good. Thanks.
