### ISSUE TITLE
OAuth token support

### ISSUE THREAD

**Issue by MohammadBoshi** [smsapi/smsapi-csharp-client#26]
Hello Folks,
i created .net core app to send sms using "SMSAPI" but i get on every request to send sms this exception:
  "The remote server returned an error: (407) authenticationrequired."
here is the code.
     try
            {
                var client = new ClientOAuth("valid token created by smsapi");
                var smsApi = new SMSFactory(client);
                var result =
                   smsApi.ActionSend()
                       .SetText("test message")
                       .SetTo("valid Number")
                       .Execute();
           }
do you have any advice for this issue?

**Comment by smsapi** [comment]
Hi,
if you have account on **smsapi.com** please use:
var smsApi = new SMSFactory(client, ProxyAddress.SmsApiCom);
instead of:
var smsApi = new SMSFactory(client);

**Comment by MohammadBoshi** [comment]
Thanks for the answer @smsapi 
I have account on smsapi.com but unfortunately i get the same error 
"The remote server returned an error: (407) authenticationrequired."

**Remak**: i am using a VPN Connection for Remote Work.
