### ISSUE TITLE
'Authorization failed'

### ISSUE THREAD

**Issue by basak-kucuk** [smsapi/smsapi-csharp-client#27]
Hello,

I am facing SMSApi.Api.ClientException: 'Authorization failed' error when I try to send SMS from my local dev environment. When I use an account from .com extension, I was using the commented-out code below and it works fine. But when I try to send from .se account, it is not working. You can find my client code below:

SMSApi.Api.IClient client = new SMSApi.Api.ClientOAuth(token);
var smsApi = new SMSApi.Api.SMSFactory(client);
//var smsApi = new SMSApi.Api.SMSFactory(client, ProxyAddress.SmsApiCom);

I have an account on smsapi.se, but when I check available proxies, I only see .pl and .com extensions.

namespace SMSApi.Api
{
    public enum ProxyAddress
    {
        SmsApiPl = 0,
        BackupSmsApiPl = 1,
        SmsApiCom = 2,
        BackupSmsApiCom = 3
    }
}

How should I configure or edit my client code to send an SMS with your API from .se account?

**Comment by jakublabno** [comment]
Hi, we're going to release new version, which will allow you to use Swedish platform as well soon.
