### ISSUE TITLE
SerializationException upon HTTP 500 response

### ISSUE THREAD

**Issue by Liebeck** [smsapi/smsapi-csharp-client#35]
Since yesterday, we've experienced multiple problems when sending SMS. About 50% of the SMS we want to send result in an HTTP 500 error from https://smsapi.io/sms.do

Your C# library is not set up in a way to deal with a HTTP 500 response. Api.Action.Base.Processreponse will throw a SerializationException from the response stream.

Using Fiddler and debugging the source code, I've looked into the responses that we receive:

```
Response:
HTTP/1.1 500 Internal Server Error
Date: Sat, 22 Apr 2023 18:21:10 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 69
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains

write tcp4 10.193.144.98:33800->85.194.241.82:443: write: broken pipe
```

or

```
HTTP/1.1 500 Internal Server Error
Date: Sat, 22 Apr 2023 18:26:14 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 165
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains

the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection
```

Besides from fixing both issues in SMSAPI, the smsapi-csharp-client should properly deal with a HTTP 500 response and not try to parse the JSON response it would normally get from a HTTP 200 response.

**Comment by mpawikowski** [comment]
Hello,

Thank you for your report, I forwarded it to our IT department for verification.

**Comment by jakublabno** [comment]
This is resolved by 3.x version

**Comment by Liebeck** [comment]
Thank you. We switched away from SMSAPI to a competitor since that critical bug was not addressed within one week and we got no help from multiple customer support agents. I'm a little bit sad that it took almost 1 year to address this bug
