### ISSUE TITLE
ActionSend return Method not found from RestSharp. 

### ISSUE THREAD

**Issue by bblazik** [smsapi/smsapi-csharp-client#36]
**Env:**
.Net 6.0, RestSharp 109.0.1

**Bug**
smsApi.ActionSend() return error with msg
Message = "Method not found: 'RestSharp.RestResponse RestSharp.RestClient.Execute(RestSharp.RestRequest, System.Threading.CancellationToken)'."

**Comment by jakublabno** [comment]
Hello, I think it's related to this thread https://github.com/smsapi/smsapi-csharp-client/issues/32#issuecomment-1513088632
We will check it and let you know soon.

**Comment by jakublabno** [comment]
Hi, please check new version - [2.2.0](https://www.nuget.org/packages/SMSAPI.pl/2.2.0)
