### ISSUE TITLE
Nie mogę pobrać klienta przez nuget do projektu pod .NET 4.5

### ISSUE THREAD

**Issue by moody19871987** [smsapi/smsapi-csharp-client#6]
Przy próbie dodania klienta SMS API przez nuget dostaję błąd:

Could not install package 'SMSAPI.pl 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Czy ktoś nie skompilował biblioteki pod .net 4.6 przez przypadek? Jeśli build został zrobiony pod niższą wersję .NET (np. 3.5), to raczej nie powinienem mieć problemu z kompilacją pod .NET 4.5.

**Comment by crashuxx** [comment]
sam source code poszedł bez binarek :) FIXED

**Comment by moody19871987** [comment]
Faktycznie, teraz działa. Dzięki!
