### ISSUE TITLE
Metoda do pobierania liczby punktów przed wysłaniem wiadomości

### ISSUE THREAD

**Issue by Misiu** [smsapi/smsapi-csharp-client#8]
Po wysłaniu SMS'a otrzymujemy w odpowiedzi ilość punktów ile dana wiadomość "kosztowała". Czy jeszcze przed wysłaniem możemy otrzymać taką informację?
Po ustawieniu tekstu metodą `SetText` chciałbym pobrać informację ile punktów dana wiadomość wykorzysta. W dokumentacji znalazłem opis algorytmu liczenia punktów, jednak oficjalna metoda (np `GetPoints`) w API byłaby dużym udogodnieniem.

**Comment by smsapi** [comment]
Można użyć parametru "Test", który zwraca odpowiedź z serwisu nie wysyłając wiadomości.

**Comment by Misiu** [comment]
@smsapi dziękuję za informację.
